version: "3.9"
services:
  postgres-lib:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "obrubov_203"
      POSTGRES_USER: "obrubov_203"
      POSTGRES_PASSWORD: "obrubov_203"
      PGDATA: "/var/lib/postgresql/data/pgdata-library"
    volumes:
      - ./docker/db/scripts/library:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
      - ./docker/db/config/library/postgresql.conf:/var/lib/postgresql/data/pgdata-library/postgresql.conf

    ports:
      - "5432:5432"
  postgres-hospital:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "obrubov_203"
      POSTGRES_USER: "obrubov_203"
      POSTGRES_PASSWORD: "obrubov_203"
      PGDATA: "/var/lib/postgresql/data/pgdata-hospital"
    volumes:
      - ./docker/db/scripts/hospital:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
      - ./docker/db/config/hospital/postgresql.conf:/var/lib/postgresql/data/pgdata-hospital/postgresql.conf
    ports:
      - "6000:5432"

  postgres-trains:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "obrubov_203"
      POSTGRES_USER: "obrubov_203"
      POSTGRES_PASSWORD: "obrubov_203"
      PGDATA: "/var/lib/postgresql/data/pgdata-trains"
    volumes:
      - ./docker/db/scripts/trains:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
      - ./docker/db/config/trains/postgresql.conf:/var/lib/postgresql/data/pgdata-trains/postgresql.conf
    ports:
      - "6111:5432"
